//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyecto02
{
    using System;
    using System.Collections.Generic;
    
    public partial class beneficiario
    {
        public int id { get; set; }
        public string nombre { get; set; }
        public string apellido_pa { get; set; }
        public string apellido_ma { get; set; }
        public Nullable<int> telefono { get; set; }
        public string correo { get; set; }
        public Nullable<System.DateTime> fecha_pago { get; set; }
    }
}
